# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teamhungary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'GoogleSignIn'
pod 'FirebaseCore'
 
pod 'FirebaseAuth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'GoogleSignInSwiftSupport'
  # Pods for teamhungary

  target 'teamhungaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'teamhungaryUITests' do
    # Pods for testing
  end

end
